# Generated by Django 5.0.1 on 2024-02-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_author_post_message_post_timeposted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likeCount',
            field=models.IntegerField(default=0),
        ),
    ]
